apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-pipeline-run
spec:
  pipelineRef:
    name: ci-pipeline

  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc

  params:
    - name: repo-url
      value: https://github.com/your-repo.git
    - name: app-name
      value: myapp
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/$NAMESPACE/myapp
