apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-pipeline
spec:
  workspaces:
    - name: shared-workspace

  params:
    - name: app-name
    - name: build-image

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: nose
      taskRef:
        name: nose
      runAfter: ["cleanup"]
      workspaces:
        - name: source
          workspace: shared-workspace

  finally:
    - name: deploy
      taskRef:
        name: deploy
      params:
        - name: app-name
          value: $(params.app-name)
        - name: build-image
          value: $(params.build-image)
